import { CorsOptions } from '@nestjs/common/interfaces/external/cors-options.interface';

export const corsConfigProduction: CorsOptions = {
  origin: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'],
  allowedHeaders: [
    'Accept',
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'X-API-Key',
    'X-HTTP-Method-Override',
    'Cache-Control',
    'Pragma',
    'Expires',
    'Last-Modified',
    'ETag',
    'If-None-Match',
    'If-Modified-Since',
    'Origin',
    'Referer',
    'User-Agent',
    'Accept-Encoding',
    'Accept-Language',
    'Connection',
    'Host',
    'X-Forwarded-For',
    'X-Real-IP',
    'X-CSRF-Token',
    'X-Frame-Options',
    'X-Content-Type-Options',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
    'Access-Control-Allow-Credentials',
  ],
  exposedHeaders: [
    'Content-Length',
    'Content-Type',
    'Date',
    'ETag',
    'Last-Modified',
    'Location',
    'Server',
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
    'X-Total-Count',
    'X-Page-Count',
    'X-Per-Page',
    'X-Current-Page',
    'Access-Control-Allow-Origin',
  ],
  credentials: true,
  maxAge: 86400,
  preflightContinue: false,
  optionsSuccessStatus: 204,
};

export const corsConfigDevelopment: CorsOptions = {
  origin: true,
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'],
  allowedHeaders: [
    'Accept',
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'X-API-Key',
    'X-HTTP-Method-Override',
    'Cache-Control',
    'Pragma',
    'Expires',
    'Last-Modified',
    'ETag',
    'If-None-Match',
    'If-Modified-Since',
    'Origin',
    'Referer',
    'User-Agent',
    'Accept-Encoding',
    'Accept-Language',
    'Connection',
    'Host',
    'X-Forwarded-For',
    'X-Real-IP',
    'X-CSRF-Token',
    'X-Frame-Options',
    'X-Content-Type-Options',
    'Access-Control-Allow-Origin',
    'Access-Control-Allow-Methods',
    'Access-Control-Allow-Headers',
    'Access-Control-Allow-Credentials',
  ],
  exposedHeaders: [
    'Content-Length',
    'Content-Type',
    'Date',
    'ETag',
    'Last-Modified',
    'Location',
    'Server',
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
    'X-Total-Count',
    'X-Page-Count',
    'X-Per-Page',
    'X-Current-Page',
    'Access-Control-Allow-Origin',
  ],
  credentials: true,
  maxAge: 86400,
  preflightContinue: false,
  optionsSuccessStatus: 204,
};

export const getCorsConfig = (): CorsOptions => {
  const isProduction = process.env.NODE_ENV === 'production';
  return isProduction ? corsConfigProduction : corsConfigDevelopment;
};
export const corsConfig = getCorsConfig();
export const corsConfigDev = corsConfigDevelopment;
