import { CorsOptions } from '@nestjs/common/interfaces/external/cors-options.interface';

export const corsConfig: CorsOptions = {
  origin: '*', // Allow all origins
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'],
  allowedHeaders: [
    'Accept',
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'X-API-Key',
    'X-HTTP-Method-Override',
    'Cache-Control',
    'Pragma',
    'Expires',
    'Last-Modified',
    'ETag',
    'If-None-Match',
    'If-Modified-Since',
    'Origin',
    'Referer',
    'User-Agent',
    'Accept-Encoding',
    'Accept-Language',
    'Connection',
    'Host',
    'X-Forwarded-For',
    'X-Real-IP',
    'X-CSRF-Token',
    'X-Frame-Options',
    'X-Content-Type-Options',
  ],
  exposedHeaders: [
    'Content-Length',
    'Content-Type',
    'Date',
    'ETag',
    'Last-Modified',
    'Location',
    'Server',
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
    'X-Total-Count',
    'X-Page-Count',
    'X-Per-Page',
    'X-Current-Page',
  ],
  credentials: false,
  maxAge: 86400,
  preflightContinue: false,
  optionsSuccessStatus: 204,
};

export const corsConfigDev: CorsOptions = {
  origin: [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:8080',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'http://127.0.0.1:8080',
  ],
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'],
  allowedHeaders: [
    'Accept',
    'Authorization',
    'Content-Type',
    'X-Requested-With',
    'X-API-Key',
    'X-HTTP-Method-Override',
    'Cache-Control',
    'Pragma',
    'Expires',
    'Last-Modified',
    'ETag',
    'If-None-Match',
    'If-Modified-Since',
    'Origin',
    'Referer',
    'User-Agent',
    'Accept-Encoding',
    'Accept-Language',
    'Connection',
    'Host',
    'X-Forwarded-For',
    'X-Real-IP',
    'X-CSRF-Token',
    'X-Frame-Options',
    'X-Content-Type-Options',
  ],
  exposedHeaders: [
    'Content-Length',
    'Content-Type',
    'Date',
    'ETag',
    'Last-Modified',
    'Location',
    'Server',
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining',
    'X-RateLimit-Reset',
    'X-Total-Count',
    'X-Page-Count',
    'X-Per-Page',
    'X-Current-Page',
  ],
  credentials: true,
  maxAge: 86400,
  preflightContinue: false,
  optionsSuccessStatus: 204,
};
